### ISSUE TITLE
Improve contrast ratio throughout site

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#190]
This seems to me a persistent issue on our site that we could address fairly easily.  Here's an example of an issue right now:
<img width="231" alt="Screen Shot 2019-04-06 at 11 50 57 AM" src="https://user-images.githubusercontent.com/4877315/55671930-104d0380-5863-11e9-9226-9a65770eaf2f.png">

Essentially, all links are not meeting the WCAG criteria!!  Here's a useful tool:

https://webaim.org/resources/contrastchecker/

**Comment by mdlama** [comment]
Here's another example with buttons:
<img width="333" alt="Screen Shot 2019-04-06 at 12 22 14 PM" src="https://user-images.githubusercontent.com/4877315/55672232-aafb1180-5866-11e9-9a00-cf2c8e6001ba.png">

**Comment by trisketz** [comment]
Big question - that color green has been a part of QUBES template colors I think since the beginning. Are we willing to change this?

**Comment by mdlama** [comment]
I would say yes, we should reconsider the color.  Keep it close, but I think accessibility is more important.

- Drew

**Comment by trisketz** [comment]
I should add about the latest pull #216. There is one place I wasn't sure how to remove the underline link. Under the publication record view - under group ownership. The image has the underline and when you hover over, the link will have bad contrast as well as the underline. The CSS that is being pulled for that section is from: /core/plugins/publications/groups/assets/css/groups.css

![Screen Shot 2019-07-24 at 1 17 21 PM](https://user-images.githubusercontent.com/21963909/61821973-b83c0c00-ae15-11e9-8cb4-b3453b5af08a.png)
![Screen Shot 2019-07-24 at 1 17 29 PM](https://user-images.githubusercontent.com/21963909/61821977-ba9e6600-ae15-11e9-8414-18c6ab8f83f0.png)

**Comment by mdlama** [comment]
I think we can override the groups.css file in that plugin by creating the following file

`/app/templates/bmc/html/plg_publications_groups/groups.css`

which can then have the following at the top of the file:

`@import url('/core/plugins/publications/groups/assets/css/groups.css');`

Would that help?

**Comment by trisketz** [comment]
I think that would, that sounds simple enough. I thought there was going to
have to be some complicated process to create an override.

**Comment by trisketz** [comment]
Override has been created and I went ahead and fixed the links on the pub record view.

**Comment by mdlama** [comment]
Hi, Jenny.  Here's a picture of the Support system after the code push. 

![Screen Shot 2019-07-30 at 2 35 59 PM](https://user-images.githubusercontent.com/4877315/62155745-b1127380-b2d7-11e9-84d5-300a4bdbd027.png)

Can we override it so that the summary text isn't bold and underlined?

**Comment by trisketz** [comment]
I also want to adjust the font on our publications macro, as well as add a border around the images. But I can't get the macro to work on my vagrant at the moment.

**Comment by trisketz** [comment]
Okie dokie. Getting rid of the underline for links update:

- Increasing contrast of body text color (darkening it a bit from #4c4c4c to #2b2b2b) increases the contrast between link color and surrounding text to pass WCAG: A standards
- I already have the link font different from surround body text. It's subtle but there, which I think works well. The font is the same font as the main navigation.
- I debated changing the hover color to a different color, mostly because it's pretty and adds nice color :) But requirements only dictate that there is a visual change on hover/focus. Right now on hover it goes to a dark blue. Debated changing it to a teal (which would still meet contrast requirements). Just wanted to throw that out there ;)
- This really is a quick change in two files. But there will be some redundant css floating around which I will want to clean up when I was fixing links in other components/plugins when we implemented the underline the first time. 

<img width="686" alt="Screen Shot 2019-10-18 at 3 43 38 PM" src="https://user-images.githubusercontent.com/21963909/67130686-5b0ae900-f1bf-11e9-8919-a9aecae59187.png">
<img width="683" alt="Screen Shot 2019-10-18 at 3 43 55 PM" src="https://user-images.githubusercontent.com/21963909/67130694-63632400-f1bf-11e9-831a-6fe595565aa4.png">
<img width="677" alt="Screen Shot 2019-10-18 at 3 44 24 PM" src="https://user-images.githubusercontent.com/21963909/67130702-678f4180-f1bf-11e9-8a3c-6239267f3a49.png">
